
version: '3.8'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapi
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=DOAN;User=sa;Password=Tri@1234;TrustServerCertificate=True 
      - Jwt__Issuer=http://localhost:5000
      - Jwt__Audience=http://localhost:5000
      - Jwt__Key=${JWT_KEY}
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD_NAME}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SmtpUsername=${SMTP_USERNAME}
      - EmailSettings__SmtpPassword=${SMTP_PASSWORD}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: myapi-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tri@1234
    volumes:
      - sqldata:/var/lib/mssql/data

volumes:
  sqldata: