
version: '3.8'

services:

  api:
    image: minhtri94/myapi:latest
    pull_policy: always
    container_name: myapi
    ports:
      - "5000:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=DOAN;User=sa;Password=Tri@1234;TrustServerCertificate=True 
      - Jwt__Issuer=http://localhost:5000
      - Jwt__Audience=http://localhost:5000
      - Jwt__Key=${JWT_KEY}
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD_NAME}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - EmailSettings__SmtpServer=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__Username=${SMTP_USERNAME}
      - EmailSettings__Password=${SMTP_PASSWORD}
      - EmailSettings__FromAddress=${SMTP_FromAddress}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    pull_policy: always
    container_name: myapi-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Tri@1234
    volumes:
      - sqldata:/var/lib/mssql/data
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Tri@1234", "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  sqldata: